language: C++
dist: Bionic
before_install:
  - sudo apt-get -y install cmake
addons:
  apt:
    update: true
before_script:
  - git clone https://github.com/catchorg/Catch2.git
  - cd Catch2 && cmake -Bbuild -H. -DBUILD_TESTING=OFF && sudo cmake --build build/ --target install && cd ..



